//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int id_usuario { get; set; }


        [Required(ErrorMessage = "OBRIGADO INFOMAR NOME")]
        [StringLength(30, ErrorMessage = "O NOME DEVE POSSUIR 30 CARACTERES")]
        public string nome { get; set; }

        [Required(ErrorMessage = "OBRIGADO INFOMAR USUARIO")]
        [StringLength(30, ErrorMessage = "O USUARIO DEVE POSSUIR 30 CARACTERES")]
        public string usuario1 { get; set; }

        [Required(ErrorMessage = "OBRIGADO INFOMAR SENHA")]
        [StringLength(10, ErrorMessage = "A SENHA DEVE POSSUIR 10 CARACTERES")]
        public string senha { get; set; }

        [Required(ErrorMessage = "OBRIGADO INFOMAR EMAIL")]
        [StringLength(30, ErrorMessage = "O EMAIL DEVE POSSUIR 30 CARACTERES")]
        public string email { get; set; }
    }
}
